[context.master.environment]
  VUE_APP_API_URL="https://api.whynot.earth/api/v0"

[[redirects]]
  from = "/.well-known/assetlinks.json"
  to = "/assetlinks.json"
  status = 200

[[redirects]]
  from = "/*"
  to = "/"
  status = 200
